<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net8.0-ios</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>MeteoApp</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>

		<!-- Display name -->
		<ApplicationTitle>MeteoApp</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.meteoapp</ApplicationId>
		<ApplicationIdGuid>4d548f4b-c83d-4fae-9d2c-9cf8027f3d25</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<AssemblyName>MeteoApp</AssemblyName>
	</PropertyGroup>

	<PropertyGroup>
		<AndroidPackageFormat>apk</AndroidPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" Color="#FFFFFF" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#00d5ff" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Appwrite" Version="0.7.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0-rc.2.24473.5" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0-rc.2.24473.5" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0-rc.2.24473.5" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
		<PackageReference Include="Microsoft.Maui.Controls.Maps" Version="8.0.92" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.10" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.92" />
		<PackageReference Include="Microsoft.Maui.Essentials" Version="8.0.92" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Models\" />
		<None Remove="Resources\ApiKey\appsettings.json" />
		<None Remove="Resources\Images\open_weather_logo.png" />
		<None Remove="sqlite-net-pcl" />
		<None Remove="Xam.Plugin.Geolocator" />
		<None Remove="Resources\.DS_Store" />
		<None Remove="Xam.Plugins.Notifier" />
		<None Remove="Acr.UserDialogs" />
		<None Remove="SQLitePCLRaw.bundle_green" />
		<None Remove="Newtonsoft.Json" />
		<None Remove="Plugin.LocalNotification" />
	</ItemGroup>
	<ItemGroup>
		<BundleResource Include="Resources\.DS_Store" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Resources\ApiKey\appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<MauiXaml Update="MapPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="MeteoItemPage.xaml">
			<SubType>Designer</SubType>
		</MauiXaml>
		<MauiXaml Update="WeatherBlazorPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="WeatherBlazorPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>
	<ItemGroup>
		<Compile Update="MapPage.xaml.cs">
			<DependentUpon>MapPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="MeteoListPage.xaml.cs">
			<DependentUpon>MeteoListPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="WeatherBlazorPage.xaml.cs">
		  <DependentUpon>WeatherBlazorPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="WeatherBlazorPage.xaml.cs">
			<DependentUpon>WeatherBlazorPage.xaml</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Update="Microsoft.Maui.Controls.Compatibility" Version="8.0.92" />
	</ItemGroup>
	<ProjectExtensions>
		<VisualStudio>
			<UserProperties XamarinHotReloadGenericExceptionInfoBarMeteoAppMauiHideInfoBar="True" />
		</VisualStudio>
	</ProjectExtensions>
</Project>
